name: Publish Packages
run-name: ${{ github.actor }} is publishing the packages
on:
  push:
    tags: ["v*"]
jobs:
  Publish-Packages:
    if: github.repository == 'planqtn/planqtn' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    environment:
      name: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build and publish PlanqTN Python package
        run: |
          hack/py_build.sh --publish
      - name: Build and publish PlanqTN CLI npm package
        run: |
          hack/cli_build.sh --publish
      - name: Publish to Docker Hub
        run: |
          hack/htn images job --build --push
          hack/htn images api --build --push
          hack/htn images ui --build --push
